chore: cpp-linter

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -102,8 +102,39 @@ jobs:
           name: notebook
           path: notebook.pdf
 
+  cpp-linter:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: read
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          persist-credentials: false
+      - uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
+          tidy-checks: ''
+          step-summary: true
+          files-changed-only: false
+          ignore: test|.github
+          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
+          format-review: true
+          tidy-review: true
+
+      - name: Fail fast?!
+        if: steps.linter.outputs.checks-failed != 0
+        run: |
+          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+          exit 1
+
   pack-include:
     runs-on: ubuntu-latest
+    needs: [cpp-linter]
     steps:
       - uses: actions/checkout@v6
       - name: Install uv
@@ -123,6 +154,7 @@ jobs:
 
   fast-test:
     runs-on: ubuntu-latest
+    needs: [cpp-linter]
     steps:
       - uses: actions/checkout@v6
       - name: Install uv
